api/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter
from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token

from api import viewsets

router = DefaultRouter()
router.register('nightmare', viewsets.NightmareViewset)

urlpatterns = [
    path(r'token-auth/', obtain_jwt_token),
    path(r'token-refresh/', refresh_jwt_token),
]

urlpatterns += router.urls

core/urls.py
from django.urls import path


urlpatterns = [
]

theNightmareWeShare/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions
from rest_framework.settings import api_settings

from theNightmareWeShare import settings

schema_view = get_schema_view(
    openapi.Info(
        title="TheNightmareWeShare API",
        default_version='BETA',
        description="enpoints de l'application the nightmare we share",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    validators=['flex', 'ssv'],
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    url(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    url(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    url(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path('admin/', admin.site.urls),
    path('markdownx/', include('markdownx.urls')),
    path('nested_admin/', include('nested_admin.urls')),
    path('api/', include('api.urls'))
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Create your models here.

nightmare/models.py
import math

from django.db import models
from django.utils import timezone
from markdownx.models import MarkdownxField


class Nightmare(models.Model):
    name = models.CharField(max_length=150)
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    date_creation = models.DateTimeField(default=timezone.now())
    completed = models.BooleanField(default=False)

    def __str__(self):
        return '{} de {}'.format(self.name, self.author)


class NightmarePart(models.Model):
    number = models.IntegerField()
    nightmare = models.ForeignKey('Nightmare', on_delete=models.CASCADE,
                                  related_name='nightmareparts')
    image = models.ImageField(upload_to='nightmare_part/', blank=True, null=True)
    text = MarkdownxField()

    def __str__(self):
        return 'n°{} de {}'.format(self.number, self.nightmare.name)


class NightmareSurvey(models.Model):
    part = models.ForeignKey('NightmarePart', on_delete=models.CASCADE,
                             related_name='nightmarsurvey')
    duration = models.DurationField()
    date_creation = models.DateTimeField(default=timezone.now())
    completed = models.BooleanField(default=False)

    def get_time_left(self):
        return int(
            round((self.date_creation + self.duration - timezone.now()).total_seconds() / 60, 0))
    # TODO faire une crontask qui vérifie régulièrement les tâches non complétée.


class NightmareSurveyProposition(models.Model):
    name = models.CharField(max_length=150)
    vote = models.IntegerField(default=0)
    survey = models.ForeignKey('NightmareSurvey', on_delete=models.CASCADE,
                               related_name='nightmaresurveypropositions')

core/templates/core/home.html
{% extends 'base.html' %}

{% block title %}The Nightmares we share - home{% endblock %}

{% block accueil_active %}active{% endblock %}

{% block body %}
    <div class="card mt-3">
        <img src="{{ last_nightmare.nightmarepart_set.first.image.url }}"
             alt="{{ last_nightmare.nightmarepart_set.first.image.name }}" class="card-img-top"/>
        <div class="card-body">
            <h3 class="card-title">{{ last_nightmare.name }}</h3>
            <p class="card-text">
                {{ last_nightmare.nightmarepart_set.first.text }}
            </p>
        </div>
        <a class="btn btn-primary"
           href="{% url 'nightmare_detail' last_nightmare.id %}">Détails</a>
        <a href="{% url 'nightmare_read' last_nightmare.id %}"
           class="btn btn-success">Lire</a>
    </div>



    <!--<editor-fold desc="Modal registerSuccess">-->
    <div class="modal fade top" id="RegisterSuccess" tabindex="-1" role="dialog"
         aria-labelledby="exampleModalPreviewLabel" aria-hidden="true">
        <div class="modal-dialog modal-sm modal-frame modal-top" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalPreviewLabel">Inscription réussie</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer
                    </button>
                </div>
            </div>
        </div>
    </div>
    <!-- Modal -->
    <!--</editor-fold>-->

    <!--<editor-fold desc="modal LoginSuccess">-->
    <div class="modal fade top" id="LoginSuccess" tabindex="-1" role="dialog"
         aria-labelledby="exampleModalPreviewLabel" aria-hidden="true">
        <div class="modal-dialog modal-sm modal-frame modal-top" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalPreviewLabel">Connection réussie</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer
                    </button>
                </div>
            </div>
        </div>
    </div>
    <!-- Modal -->
    <!--</editor-fold>-->

    <!--<editor-fold desc="modal LogoutSuccess">-->
    <div class="modal fade top" id="LogoutSuccess" tabindex="-1" role="dialog"
         aria-labelledby="exampleModalPreviewLabel" aria-hidden="true">
        <div class="modal-dialog modal-sm modal-frame modal-top" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalPreviewLabel">Déconnection réussie</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer
                    </button>
                </div>
            </div>
        </div>
    </div>
    <!-- Modal -->
    <!--</editor-fold>-->
{% endblock %}

{% block js %}
    {% if statut == 'register_success' %}
        <script>
            $(document).ready(function () {
                $('#RegisterSuccess').modal('toggle')
            });
        </script>
    {% endif %}

    {% if statut == 'login_success' %}
        <script>
            $(document).ready(function () {
                $('#LoginSuccess').modal('toggle')
            });
        </script>
    {% endif %}

    {% if statut == 'logout_success' %}
        <script>
            $(document).ready(function () {
                $('#LogoutSuccess').modal('toggle')
            });
        </script>
    {% endif %}
{% endblock %}

core/templates/core/login.html
{% extends 'base.html' %}

{% block title %}The Nightmares we share - home{% endblock %}

{% block accueil_active %}active{% endblock %}

{% block body %}
    <div class="card mt-3">
        <div class="card-body">
            <h3 class="card-title">Connection</h3>
            <form class="text-center p-5" action="{% url 'core_login' %}" method="post">
                {% csrf_token %}
                {{ form.as_md_div }}
                <input type="submit" class="btn btn-primary"/>
            </form>
        </div>
    </div>
{% endblock %}

core/templates/core/register.html
{% extends 'base.html' %}

{% block title %}The Nightmares we share - home{% endblock %}

{% block accueil_active %}active{% endblock %}

{% block body %}
    <div class="card mt-3">
        <div class="card-body">
            <h3 class="card-title">Inscription</h3>
            <form class="text-center p-5" action="{% url 'core_register' %}" method="post">
                {% csrf_token %}
                {{ form.as_md_div }}
                <input type="submit" class="btn btn-primary"/>
            </form>
        </div>
    </div>
{% endblock %}

nightmare/templates/nightmare/create.html
{% extends 'base.html' %}
{% load static %}
{% load markdownx %}

{% block title %}The Nightmares we share - read{% endblock %}

{% block nightmares_active %}active{% endblock %}

{% block body %}
    <div class="card mt-3 p-3" xmlns="http://www.w3.org/1999/html">
        <div class="card-body">
            <h4 class="card-title">Nouveau cauchemar</h4>
            <hr/>
            <form class="text-center p-5" action="{% url 'core_register' %}" method="post">
                {% csrf_token %}
                {{ form.as_md_div }}
                <input type="submit" class="btn btn-primary"/>
            </form>
        </div>
    </div>
{% endblock %}

nightmare/templates/nightmare/detail.html
{% extends 'base.html' %}
{% load static %}
{% load markdownx %}

{% block title %}The Nightmares we share - read{% endblock %}

{% block nightmares_active %}active{% endblock %}

{% block body %}
    <div class="card mt-4">
        <img class="card-img-top" src="{{ first_part.image.url }}"
             alt="{{ first_part.image.name }}"/>
        <div class="card-body">
            <h4 class="card-title">{{ nightmare.name }}</h4>
            <h5 class="card-subtitle text-black-50">de {{ nightmare.author.username }}</h5>
            <hr/>
            nombre de chapitres : {{ nb_chapitre }}
            <br/>
            date de création : {{ nightmare.date_creation.date }}
            à {{ nightmare.date_creation.time }}
            <hr/>
            <p class="card-text">
                {{ first_part.text }}
            </p>
            <hr/>
            <a href="{% url 'nightmare_read' nightmare.id %}" class="d-flex justify-content-end">
                <h5>
                    Lire <i class="fa fa-angle-double-right"></i>
                </h5>
            </a>
            <a href="{% url 'nightmare_home' %}" class="text-danger d-flex justify-content-between">
                <h5>
                    <i class="fa fa-angle-double-left"></i> Retour
                </h5>
            </a>
        </div>
    </div>
{% endblock %}

nightmare/templates/nightmare/home.html
{% extends 'base.html' %}
{% load static %}
{% load markdownx %}

{% block nightmares_active %}active{% endblock %}
{% block title %}The Nightmares we share - nightmares{% endblock %}

{% block body %}
    <div class="col-6 offset-3">
        {% for nightmare in nightmares %}
            <!-- Card -->
            <div class="card mb-2 mt-2">
                {% if nightmare.nightmarepart_set.first.image %}
                    <!-- Card image -->
                    <img class="card-img-top"
                         src="{{ nightmare.nightmarepart_set.first.image.url }}"
                         alt="{{ part.image.name }}">
                {% endif %}
                <!-- Card content -->
                <div class="card-body">
                    <!-- Title -->
                    <h4 class="card-title"><a>{{ nightmare.name }}</a></h4>
                    <!-- Text -->
                    <p class="card-text">{{ nightmare.nightmarepart_set.first.text | truncatewords:100 | markdown }}</p>
                    <!-- Button -->
                    <a class="btn btn-primary"
                       href="{% url 'nightmare_detail' nightmare.id %}">Détails</a>
                    <a href="{% url 'nightmare_read' nightmare.id %}"
                       class="btn btn-success">Lire</a>
                </div>
            </div>
            <!-- Card -->
        {% endfor %}
    </div>
{% endblock %}

nightmare/templates/nightmare/read.html
{% extends 'base.html' %}
{% load static %}
{% load markdownx %}

{% block title %}The Nightmares we share - read{% endblock %}

{% block nightmares_active %}active{% endblock %}

{% block body %}
    <div class="col-8 offset-2">
        {% for part in nightmare.nightmarepart_set.all %}
            <!-- Card -->
            <div class="card mb-5 mt-5 z-depth-4">

                {% if part.image %}
                    <!-- Card image -->
                    <img class="card-img-top" src="{{ part.image.url }}"
                         alt="Card image cap">
                {% endif %}

                <!-- Card content -->
                <div class="card-body">

                    <!-- Title -->
                    <h4 class="card-title"><a>{{ nightmare.name }} - {{ part.number }}</a></h4>
                    <!-- Text -->
                    <p class="card-text">{{ part.text | markdown }}</p>

                    {% if part.nightmaresurvey_set.last %}
                        <hr/>
                        {% if part.nightmaresurvey_set.last.completed or part.nightmaresurvey_set.last.get_time_left <= 0 %}
                            <table class="table">
                                {% for choice in part.nightmaresurvey_set.last.nightmaresurveyproposition_set.all %}
                                    <thead>
                                    <tr>
                                        <th scope="col">{{ choice.name }}</th>
                                        <th scope="col">{{ choice.vote }}</th>
                                    </tr>
                                    </thead>
                                {% endfor %}
                            </table>
                        {% else %}
                            <form class="text-left">
                                temps restant :
                                {{ part.nightmaresurvey_set.last.get_time_left }} mn
                                <div class="form-check">
                                    {% for choice in part.nightmaresurvey_set.last.nightmaresurveyproposition_set.all %}
                                        <div class="custom-control custom-radio">
                                            <input type="radio" class="custom-control-input"
                                                   id="{{ choice.name }}"
                                                   name="{{ part.id }}Radios">
                                            <label class="custom-control-label"
                                                   for="{{ choice.name }}">{{ choice.name }}</label>
                                        </div>
                                    {% endfor %}
                                </div>
                                <input type="submit" class="btn btn-primary" value="Envoyer"/>
                            </form>
                        {% endif %}
                    {% endif %}

                </div>

            </div>
            <!-- Card -->
        {% endfor %}
    </div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <!-- Font Awesome -->
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
    <!-- Your custom styles (optional) -->
    {% block css %}{% endblock %}
</head>

<body>
<!-- Start your project here-->
<!--Navbar-->
<nav class="navbar navbar-expand-lg navbar-dark primary-color">
    <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#menu"
            aria-controls="navbarTogglerDemo01" aria-expanded="false"
            aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <!-- Navbar brand -->
    <a class="navbar-brand" href="{% url 'core_home' %}">The Nightmares we share</a>

    <!-- Collapsible content -->
    <div class="collapse navbar-collapse" id="menu">
        <!-- Links -->
        <ul class="navbar-nav mr-auto ml-auto">
            <li class="nav-item {% block accueil_active %}{% endblock %}">
                <a class="nav-link" href="{% url 'core_home' %}">accueil</a>
            </li>
            <li class="nav-item {% block nightmares_active %}{% endblock %}">
                <a class="nav-link" href="{% url 'nightmare_home' %}">Nightmares</a>
            </li>
            {% if not user.is_authenticated %}
                <li class="nav-item {% block connexion_active %}{% endblock %}">
                    <a class="nav-link" href="{% url 'core_login' %}">Connexion</a>
                </li>
                <li class="nav-item {% block enregistrement_active %}{% endblock %}">
                    <a class="nav-link" href="{% url 'core_register' %}">Créer un compte</a>
                </li>
            {% else %}
                <li class="nav-item {% block create_active %}{% endblock %}">
                    <a class="nav-link" href="{% url 'nightmare_create' %}">Nouveau cauchemar</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'core_logout' %}">Déconnection</a>
                </li>
            {% endif %}
        </ul>
        <!-- Links -->

        <form class="form-inline">
            <div class="md-form my-0">
                <input class="form-control mr-sm-2" type="text" placeholder="Recherche"
                       aria-label="Recherche">
            </div>
        </form>
    </div>
    <!-- Collapsible content -->
</nav>
<!--/.Navbar-->
<div class="container">
    {% block body %}{% endblock %}
</div>
<!-- /Start your project here-->

<!-- SCRIPTS -->
<!-- JQuery -->
<script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>

{% block js %}{% endblock %}
</body>

</html>